config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "lists#index"
  resources :lists do
    resources :movies, only: [:show] do
      resources :bookmarks, only: [:destroy]
    end
    resources :bookmarks, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }

  validates :movie_id, uniqueness: {scope: :list_id, message: "is already in the list"}

end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, -> { distinct }, through: :bookmarks

  validates :name, presence: true, uniqueness: true

  def movies
    self.bookmarks.map { |bookmark| bookmark.movie}
  end

  def bookmark(id)
    Bookmark.find_by(list: self, movie_id: id)
  end

  def bookmark_comment(id)
    Bookmark.find_by(list: self, movie_id: id).comment
  end
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
require "json"
require "open-uri"

class BookmarksController < ApplicationController
  before_action :set_list

  def new
    movies_json = load_movies_json
    @movies = []
    create_movies(movies_json, @movies)
    @movies.sort_by!(&:vote_count).reverse!
  end

  def create
    if Movie.find(movie_params[:id])
      movie = Movie.find(movie_params[:id])
    else
      movie = Movie.create!(movie_params)
    end
    create_bookmark(@list, movie)
  end

  def destroy
    @bookmark = Bookmark.find_by(list: @list, movie_id: params[:movie_id])
    @bookmark.destroy
    redirect_to list_path(List.find(params[:list_id])), status: :see_other
  end

  private

  def load_movies_json
    query = params[:query]
    url = "https://api.themoviedb.org/3/search/movie?query=#{query}&include_adult=false&language=en-US&page=1%22&api_key=#{ENV['TMDB_API_KEY']}"
    JSON.parse(URI.open(url).read)["results"]
  end

  def create_movies(movie_json, movie_array)
    movie_json.each do |movie|
      saved_movie = Movie.find_by(title: movie["title"], description:  movie["overview"])
      if saved_movie
        movie_array << saved_movie
      else
        movie_array << Movie.new(
          title: movie["title"],
          rating: movie["vote_average"].round(2),
          year: movie["release_date"][0..3],
          description:  movie["overview"],
          poster_url: "http://image.tmdb.org/t/p/w500/#{movie["backdrop_path"] || movie["poster_path"]}",
          vote_count: movie["vote_count"]
          )
      end
    end
  end

  def movie_params
    params.require(:movie).permit(:id, :year, :title, :rating, :vote_count, :description, :poster_url)
  end

  def set_list
    @list = List.find(params[:list_id])
  end

  def create_bookmark(list, movie)
    bookmark = Bookmark.create(list: list, movie: movie, comment: params[:comment])
    if bookmark.save
      redirect_to list_path(list)
    else
      render "lists/show", status: :unprocessable_entity
    end
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def new
    @list = List.new
  end

  def create
    @list = List.create(list_params)
    @list.save
    redirect_to lists_path()
  end

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  private

  def list_params
    params.require(:list).permit(:name, :image_url)
  end
end

app/controllers/movies_controller.rb
require "json"
require "open-uri"

class MoviesController < ApplicationController
  def index
    query = params[:query]
    url = "https://api.themoviedb.org/3/search/movie?query=#{query}&include_adult=false&language=en-US&page=1%22&api_key=#{ENV['TMDB_API_KEY']}"
    movies_json = JSON.parse(URI.open(url).read)["results"]

    @movies = []
    movies_json.each do |movie|
      if Movie.find_by(title: movie["title"], description:  movie["overview"])
        @movies << Movie.find_by(title: movie["title"], description:  movie["overview"])
      else
        @movies << Movie.new(
          title: movie["title"],
          rating: movie["vote_average"].round(2),
          year: movie["release_date"][0..3],
          description:  movie["overview"],
          poster_url: "http://image.tmdb.org/t/p/w500/#{movie["backdrop_path"] || movie["poster_path"]}",
          vote_count: movie["vote_count"]
          )
      end
    end
    @movies.sort_by!(&:vote_count).reverse!
    @list = List.find(params[:list_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<%= render "shared/movie_grid", movies: @movies, list: @list %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoviesAndShowsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/banner" %>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="homebanner"></div>
<div class="container pt-3">
  <p><b>My lists</b></p>
  <div class="list-cards d-grid">
    <% @lists.each do |list| %>
      <a href="lists/<%= list.id %>">
        <div class="list-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= list.image_url %>)" >
          <%= list.name %>
        </div>
      </a>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.input :image_url %>
  <%= f.button :submit, class:"btn btn-primary" %>
<% end %>

app/views/lists/show.html.erb
<div class="list-image d-flex flex-column" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= @list.image_url %>)">
  <%= @list.name %>
  <div class="col-sm-8 my-3">
    <%= form_with url: new_list_bookmark_path(@list), method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Search a movie"
        %>
      <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
<%= render "shared/movie_grid", list: @list, movies: @list.movies %>

app/views/shared/_banner.html.erb
<div class="banner d-flex justify-content-between">
  <%= image_tag "logo.jpg", class: "ms-3" %>
  <div class="links d-flex align-items-center pe-3">
    <%= link_to "My lists", lists_path(), class: "pe-2" %>
    <%= link_to "New list", new_list_path() %>
  </div>
</div>

app/views/shared/_movie_grid.erb
<div class="container pt-3">
  <div class="cards">
    <% movies.each do |movie| %>
      <div class="card mb-3">
      <img src="<%= movie.poster_url %>" class="card-img-top" alt="">
      <div class="card-body">
        <h5 class="card-title"><%= movie.title || movie["title"] %> (<%= movie.year %>) - <%= movie.rating || movie["vote_average"] %> ⭐</h5>
        <p class="card-text"><%= movie.description  || movie["overview"]  %></p>
        <div class="card-text d-flex justify-content-between" data-controller="bookmark">
          <div class="bookmark d-flex">
            <i class="fa-solid fa-quote-left"></i>
            <% if list.bookmark(movie.id) %>
              <small class="text-muted"><%= list.bookmark_comment(movie.id) %></small>
            <% else %>
              <%= form_with url: list_bookmarks_path(list, :movie => movie.attributes), method: :post, class: "ps-2 d-none d-flex", data: { bookmark_target: "form"} do %>
                <%= text_field_tag :comment,
                      params[:comment],
                      class: "form-control form-control-sm",
                      placeholder: "Add a comment here" %>
                <%= submit_tag "Add comment",
                  class: "btn btn-primary btn-sm" %>
              <% end %>
            <% end %>
          </div>
          <div class="append_list">
            <% unless list.movies.include?(movie) %>
              <div data-action="click->bookmark#toggle"><%= "Add to #{list.name}" %></div>
            <% else %>
              <%= link_to "Delete movie from list",
                  list_movie_bookmark_path(list, movie, Bookmark.find_by(list_id: list.id, movie_id: movie.id)),
                  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
                  class: "text-danger" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>